services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres_pgvector
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: PgVectorWithCSharpDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/Infra/Init:/docker-entrypoint-initdb.d
    
volumes:
  pgdata:
