@BASE_URL = http://localhost
@PORT = 5034

###

# Teste GET /v1/products - Lista todos os produtos
GET {{BASE_URL}}:{{PORT}}/v1/products

###

# Teste POST /v1/products - Cria um novo produto
POST {{BASE_URL}}:{{PORT}}/v1/products
Content-Type: application/json

{
  "title": "Produto de Teste",
  "category": "Categoria de Teste"
}

###

# Teste GET /v1/seed - Semeia o banco com recomendações
GET {{BASE_URL}}:{{PORT}}/v1/seed

###

# Teste POST /v1/prompt - Busca recomendações baseadas em uma pergunta
POST {{BASE_URL}}:{{PORT}}/v1/prompt
Content-Type: application/json

{
  "prompt": "O que você recomenda de cafe arábico?"
}

